# Generated by Django 4.2.6 on 2023-11-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.IntegerField()),
                ('upper_bound', models.IntegerField()),
                ('reward_level', models.IntegerField()),
                ('reward_money', models.IntegerField()),
                ('rang', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_arena', to='arena.arena')),
                ('toad1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_battle_toad', to='toad.toad')),
                ('toad2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_battle_toad', to='toad.toad')),
            ],
        ),
    ]
