# Generated by Django 4.2.6 on 2023-11-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('money', models.IntegerField()),
                ('curr_level', models.IntegerField()),
                ('level_progress', models.IntegerField()),
                ('health', models.IntegerField()),
                ('backpack', models.CharField(max_length=100)),
                ('last_feed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkToad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('toad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toad_at_work', to='toad.toad')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_of_toad', to='work.work')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('ignore', models.BooleanField()),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to='toad.toad')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='toad.toad')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_friend', to='toad.toad')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_friend', to='toad.toad')),
            ],
        ),
        migrations.CreateModel(
            name='Backpacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toad_with_backpack', to='toad.toad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_backpack', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Arena_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_toad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toad_send_request', to='toad.toad')),
            ],
        ),
    ]
